---
title: 'DATA 533: ASSIGNMENT 2 - PROPOSAL'
author: "Claudia Nikel - NGHIA PHAN TRONG "
date: "11/20/2019"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Food and Beverage Management Package 

### Package Description

    This package is used to manage businesses in Food and Beverage. There are two subpackages Operation Management and Human Resource Management 
  
#### Subpackage 1: Operation Management   
* FnBClass Module : allowing to create objests related to the operation of FnB Business 
  - Class FnB : 
    an instance of this class has those attributes: address, instorestaff, area, revenue
  - Class DeliveryBusiness 
    this class is inherited from FnB class with additional attributess: deliverychannel   
  
* FnBFunction.py 
  - comparerevenue(A,B)   : show the bar plot with the revenues of FnB business in a list passed to the function
  - stafftransfer(A,B,n)  : transfer n staffs from group B to group A. Return TURE if the transfer is successful and FALSE if not    
    
    

#### Subpackage 2: Human Resource Management
* StaffClass Module : allowing to create objests to manage employees in a FnB Business 
  - Class Staff
    an instance of this class has attributes: id, name, salary, entry year, last_promotion_year, store name, title, supervisor
  - Class Management
    this class is inherited from FnB class with additional attributess: stafflist (include id of the staffs under his/her management)
* HRfunction.py
  - promotioncheck(employeelist) : every 2 year, the salary of an employee will be increased 10%. This function will validate a list of employee and apply promotion if possible.

  
     

